-- 8 Pre-seeded Libraries
INSERT INTO `libraries` (`name`, `city`, `state`) VALUES
('Central City Library', 'Bengaluru', 'Karnataka'),
('Riverside Public Library', 'Mumbai', 'Maharashtra'),
('Mountainview Library', 'Kolkata', 'West Bengal'),
('Lakeside Community Library', 'Manipal', 'Karnataka'),
('Downtown Knowledge Hub', 'Dharwad', 'Karnataka'),
('Suburban Book Haven', 'Shivamogga', 'Karnataka'),
('Coastal Reads Library', 'Chennai', 'Tamil Nadu'),
('Historic Town Library', 'Hyderabad', 'Telangana');

--8 Pre-seeded Books
INSERT INTO `books` (`title`, `author`, `genre`, `isbn`, `description`) VALUES
('The Great Adventure', 'John Smith', 'Fiction', '978-3-16-148410-0', 'An epic tale of adventure and discovery.'),
('Mystery of the Old Mansion', 'Jane Doe', 'Mystery', '978-1-23-456789-0', 'A thrilling mystery set in a haunted mansion.'),
('Science Wonders', 'Albert Newton', 'Science', '978-0-12-345678-9', 'Exploring the wonders of science and technology.'),
('History Unveiled', 'Mary Johnson', 'History', '978-9-87-654321-0', 'A deep dive into historical events that shaped the world.'),
('Cooking Made Easy', 'Chef Alex', 'Cooking', '978-4-56-789012-3', 'Delicious recipes and cooking tips for everyone.'),
('The Art of Painting', 'Lisa Brown', 'Art', '978-5-67-890123-4', 'A guide to mastering the art of painting.'),
('Travel the World', 'David Wilson', 'Travel', '978-6-78-901234-5', 'Tips and stories from traveling around the globe.'),
('Gardening Basics', 'Emma Davis', 'Gardening', '978-7-89-012345-6', 'A beginners guide to gardening and plant care.');

-- Mapping Books to Libraries with availability and price
INSERT INTO `library_books` (`library_id`, `book_id`, `available_count`, `price`) VALUES
(1, 1, 5, 10.99),
(1, 2, 3, 12.50),
(2, 3, 4, 15.00),
(2, 4, 2, 9.99),
(3, 5, 6, 20.00),
(3, 6, 1, 25.00),
(4, 7, 7, 18.75),
(4, 8, 8, 14.30),
(5, 1, 2, 11.50),
(5, 3, 5, 16.00),
(6, 2, 4, 13.25),
(6, 4, 3, 10.50),
(7, 5, 5, 19.99),
(7, 7, 6, 17.80),
(8, 6, 2, 26.00),
(8, 8, 9, 15.40);

-- Sample Users

-- Library Images (at least 4 images for each library, one primary)
INSERT INTO `library_images` (`library_id`, `is_primary`, `image_url`) VALUES
(1, TRUE, 'assets/images/libraries/library1_img1.jpg'),
(1, FALSE, 'assets/images/libraries/library1_img2.jpg'),
(1, FALSE, 'assets/images/libraries/library1_img3.jpg'),
(1, FALSE, 'assets/images/libraries/library1_img4.jpg'),
(2, TRUE, 'assets/images/libraries/library2_img1.jpg'),
(2, FALSE, 'assets/images/libraries/library2_img2.jpg'),
(2, FALSE, 'assets/images/libraries/library2_img3.jpg'),
(2, FALSE, 'assets/images/libraries/library2_img4.jpg'),
(3, TRUE, 'assets/images/libraries/library3_img1.jpg'),
(3, FALSE, 'assets/images/libraries/library3_img2.jpg'),
(3, FALSE, 'assets/images/libraries/library3_img3.jpg'),
(3, FALSE, 'assets/images/libraries/library3_img4.jpg'),
(4, TRUE, 'assets/images/libraries/library4_img1.jpg'),
(4, FALSE, 'assets/images/libraries/library4_img2.jpg'),
(4, FALSE, 'assets/images/libraries/library4_img3.jpg'),
(4, FALSE, 'assets/images/libraries/library4_img4.jpg'),
(5, TRUE, 'assets/images/libraries/library5_img1.jpg'),
(5, FALSE, 'assets/images/libraries/library5_img2.jpg'),
(5, FALSE, 'assets/images/libraries/library5_img3.jpg'),
(5, FALSE, 'assets/images/libraries/library5_img4.jpg'),
(6, TRUE, 'assets/images/libraries/library6_img1.jpg'),
(6, FALSE, 'assets/images/libraries/library6_img2.jpg'),
(6, FALSE, 'assets/images/libraries/library6_img3.jpg'),
(6, FALSE, 'assets/images/libraries/library6_img4.jpg'),
(7, TRUE, 'assets/images/libraries/library7_img1.jpg'),
(7, FALSE, 'assets/images/libraries/library7_img2.jpg'),
(7, FALSE, 'assets/images/libraries/library7_img3.jpg'),
(7, FALSE, 'assets/images/libraries/library7_img4.jpg'),
(8, TRUE, 'assets/images/libraries/library8_img1.jpg'),
(8, FALSE, 'assets/images/libraries/library8_img2.jpg'),
(8, FALSE, 'assets/images/libraries/library8_img3.jpg'),
(8, FALSE, 'assets/images/libraries/library8_img4.jpg');

-- Book Images (at least 5 images for each book, one primary)
INSERT INTO `book_images` (`book_id`, `is_primary`, `image_url`) VALUES
(1, TRUE, 'assets/images/books/book1_img1.jpg'),
(1, FALSE, 'assets/images/books/book1_img2.jpg'),
(1, FALSE, 'assets/images/books/book1_img3.jpg'),
(1, FALSE, 'assets/images/books/book1_img4.jpg'),
(1, FALSE, 'assets/images/books/book1_img5.jpg'),
(2, TRUE, 'assets/images/books/book2_img1.jpg'),
(2, FALSE, 'assets/images/books/book2_img2.jpg'),
(2, FALSE, 'assets/images/books/book2_img3.jpg'),
(2, FALSE, 'assets/images/books/book2_img4.jpg'),
(2, FALSE, 'assets/images/books/book2_img5.jpg'),
(3, TRUE, 'assets/images/books/book3_img1.jpg'),
(3, FALSE, 'assets/images/books/book3_img2.jpg'),
(3, FALSE, 'assets/images/books/book3_img3.jpg'),
(3, FALSE, 'assets/images/books/book3_img4.jpg'),
(3, FALSE, 'assets/images/books/book3_img5.jpg'),
(4, TRUE, 'assets/images/books/book4_img1.jpg'),
(4, FALSE, 'assets/images/books/book4_img2.jpg'),
(4, FALSE, 'assets/images/books/book4_img3.jpg'),
(4, FALSE, 'assets/images/books/book4_img4.jpg'),
(4, FALSE, 'assets/images/books/book4_img5.jpg'),
(5, TRUE, 'assets/images/books/book5_img1.jpg'),
(5, FALSE, 'assets/images/books/book5_img2.jpg'),
(5, FALSE, 'assets/images/books/book5_img3.jpg'),
(5, FALSE, 'assets/images/books/book5_img4.jpg'),
(5, FALSE, 'assets/images/books/book5_img5.jpg'),
(6, TRUE, 'assets/images/books/book6_img1.jpg'),
(6, FALSE, 'assets/images/books/book6_img2.jpg'),
(6, FALSE, 'assets/images/books/book6_img3.jpg'),
(6, FALSE, 'assets/images/books/book6_img4.jpg'),
(6, FALSE, 'assets/images/books/book6_img5.jpg'),
(7, TRUE, 'assets/images/books/book7_img1.jpg'),
(7, FALSE, 'assets/images/books/book7_img2.jpg'),
(7, FALSE, 'assets/images/books/book7_img3.jpg'),
(7, FALSE, 'assets/images/books/book7_img4.jpg'),
(7, FALSE, 'assets/images/books/book7_img5.jpg'),
(8, TRUE, 'assets/images/books/book8_img1.jpg'),
(8, FALSE, 'assets/images/books/book8_img2.jpg'),
(8, FALSE, 'assets/images/books/book8_img3.jpg'),
(8, FALSE, 'assets/images/books/book8_img4.jpg'),
(8, FALSE, 'assets/images/books/book8_img5.jpg');